name 'selenium-grid-extras'
maintainer 'Shawn McCarthy'
maintainer_email 'shawn.mccarthy3@gmail.com'
license 'all_rights'
description 'Installs/Configures selenium-grid-extras'
long_description 'Installs/Configures selenium-grid-extras'
version '0.1.0'
